#ifndef __CONST_H__
#define __CONST_H__

#include <stdio.h>

#define GAME_VERSION	0x130
#define GAME_SIGNATURE	"h5nc"

#define M_PATHMAX		260	//_MAX_PATH
#define M_STRMAX		0x80
#define M_STRKEYMAX		0x40
#define M_MESSAGESTRMAX 0x100
#define M_STRITOAMAX	0x10

#define M_FPS	60.0f


// Zorder
enum
{
	ZORDER_BG		= 0,
	ZORDER_MENU_10	= 10,
	ZORDER_MENU_9,
	ZORDER_MENU_8,
	ZORDER_MENU_7,
	ZORDER_MENU_6,
	ZORDER_MENU_5,
	ZORDER_MENU_4,
	ZORDER_MENU_3,
	ZORDER_MENU_2,
	ZORDER_MENU_1,
	ZORDER_MENU_0,
	ZORDER_FG		= 0x7fffffff,
};

#endif

// Assert
#define ASSERTSTR_SECONDSINGLETON	"Attempted to allocate a second instance of a singleton."

#define ERRORSTR_TITLE				"Error!"

#define M_SCREEN_WIDTH	960.0f
#define M_SCREEN_HEIGHT	640.0f
#define M_SCREEN_XCENTER	(M_SCREEN_WIDTH/2.0f)
#define M_SCREEN_YCENTER	(M_SCREEN_HEIGHT/2.0f)
#define M_SCREEN_Z			(M_SCREEN_WIDTH/2.0f)

#define M_CCACTIONFLAG_NULL		0x0000
#define M_CCACTIONFLAG_IN		0x0001
#define M_CCACTIONFLAG_OUT		0x0002
#define M_CCACTIONFLAG_INOUT	(M_CCACTIONFLAG_IN|M_CCACTIONFLAG_OUT)
#define M_CCACTIONFLAG_TO		0x0010
#define M_CCACTIONFLAG_BY		0x0020

#define M_CCEVENTTAG_NULL		0x0000
#define M_CCEVENTTAG_ENTER		0x0001
#define M_CCEVENTTAG_LEAVE		0x0002

#define M_CCTOUCHINDICATOR_BEGAN		0x01
#define M_CCTOUCHINDICATOR_MOVED		0x02
#define M_CCTOUCHINDICATOR_LASTMOVED	0x03
#define M_CCTOUCHINDICATOR_ENDED		0x04
#define M_CCTOUCHINDICATOR_CANCELED		0x05

#define M_CCTOUCH_TAP			0x00
#define M_CCTOUCH_HOLD			0x01
#define M_CCTOUCH_MOVE			0x02
#define M_CCTOUCH_HOLDANDMOVE	(M_CCTOUCH_HOLD|M_CCTOUCH_MOVE)

#define M_USERNAMEMAX	13
#define M_HISCOREMAX	15

#define M_STAGEMISSIONMAX	50
#define M_STAGEMAX			8
#define M_HELPTYPEMAX		5
#define M_ITEMTYPEMAX		8

#define M_GAMEHPMAX	10000
#define M_GAMEAPMAX	10000
#define M_GAMESPMAX	4

#define LOG_FILENAME		"log.log"
#define INI_FILENAME		"config.ini"
#define DATA_FILENAME		"data.dat"

#define M_TOUCH_ALLOWABLEMOVEMENT		10.0f
#define M_TOUCH_MINIMUMPRESSDURATION	0.5f
#define M_TOUCH_DOUBLEPRESSWAITDURATION	0.1f

#define M_TOUCHGESTURE_UNKNOWN			0x00
#define M_TOUCHGESTURE_ONE_NOMOVE		0x10
#define M_TOUCHGESTURE_ONE_MOVED		0x11
#define M_TOUCHGESTURE_TWO_NOMOVE		0x20
#define M_TOUCHGESTURE_TWO_MOVED		0x21

#define M_WEAPON_LASER	0
#define M_WEAPON_BOMB	1
#define M_WEAPON_SNIPER	2

#define M_TOUCHMAX	2
#define M_ENEMY_ELAYERMAX	4

#define M_WEAPONTYPEMAX 3

#define M_TURNMAX	0xfff;

#define M_MISSIONTYPE_TYPEMASK	0xf0
#define M_MISSIONTYPE_MOVIE		0x10
#define M_MISSIONTYPE_STORY		0x20
#define M_MISSIONTYPE_BOSS		0x30
#define M_MISSIONTYPE_FREE		0x40
#define M_MISSIONTYPE_GOLDENEGG	0x50
#define M_MISSIONTYPE_SURVIVAL	0x80

#define M_MISSIONTYPE_AIMMASK	0x0f
#define M_MISSIONTYPE_NORMAL	0x01
#define M_MISSIONTYPE_TARGET	0x02
#define M_MISSIONTYPE_DEFEND	0x03
#define M_MISSIONTYPE_SUICIDE	0x04

#define M_ENEMYTYPEMAX	10

#define M_MISSIONSTATE_PROGRESSING	0x00
#define M_MISSIONSTATE_CLEAR		0x01
#define M_MISSIONSTATE_FAILED		0x02

#define M_MISSIONGOLDENEGGMAX	3